version: '3.9'
services:
    server:
        build: ./src
        ports:
            - '8080:8080'
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
    database:
        image: postgres
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
